WebApplication11/Controllers/NonWorkingDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using WebApplication11.Models;

namespace WebApplication11.Controllers
{
    [Authorize(Roles = "admin")]
    public class NonWorkingDayController : Controller
    {
        ApplicationDbContext NonWorkingDayContext = new ApplicationDbContext();

        // GET: Upload
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        
        public ActionResult UploadFile()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            StreamReader datNonWork = null;
            try
            {

                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadedFiles"), _FileName);
                    file.SaveAs(_path);

                    datNonWork = new StreamReader(_path);
                    string rowString;
                    while ((rowString = datNonWork.ReadLine()) != null)
                    {
                        NonWorkingDay nonWorkingDay = new NonWorkingDay();
                        string[] str = rowString.Split(';');
                        nonWorkingDay.DateID = Convert.ToDateTime(str[0]);
                        nonWorkingDay.Description = str[1];
                        NonWorkingDayContext.nonWorkingDays.Add(nonWorkingDay);

                    }
                    NonWorkingDayContext.SaveChanges();
                }

                ViewBag.Message = "File Uploaded Successfully!!";
                return View();
            }
            catch (Exception ex)
            {

                ViewBag.Message = "File upload failed!! " + ex.Message;
                return View();
            }
            finally
            {
                datNonWork.Close();
            }
        }





    }
}

WebApplication11/Controllers/RequestHolidayController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication11.Models;
using WebApplication11.ViewModels;

namespace WebApplication11.Controllers
{
    
    public class RequestHolidayController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        
        // GET: RequestHoliday
        [HttpGet]
        [Authorize(Roles ="manager, admin")]
        public ActionResult Index()
        {
            DataSet dt = new DataSet();
            //List<ApplicationUser> users = new List<ApplicationUser>();
            ApplicationUser currentUser = new ApplicationUser();
            string logUserEmail = User.Identity.GetUserName();
            if (logUserEmail != "")
            {
                currentUser = context.Users.Where(x => x.Email.Equals(logUserEmail)).FirstOrDefault();

                //var query = from usr in context.Users
                //            join  hol in context.holidays on usr equals hol.Employee
                //            where (hol.Status == 0 && hol.Manager.Equals(currentUser.Id))
                //            select new (fName=usr.FirstName, usr.LastName, usr.Email, hol.StartDate, hol.EndDate);

                var results = (from h in context.holidays.Where(p=>p.Manager==currentUser.Id && p.Status==0)
                              join u in context.Users
                              on h.Employee equals u.Id                           
                              select new HolidayViewModel
                              {
                                  FirstName = u.FirstName,
                                  LastName = u.LastName,
                                  Email = u.Email,
                                  StartDate = h.StartDate,
                                  EndDate = h.EndDate,
                                  RequestID = h.RequestID
                              }).ToList();

                //var results = context.Users.Join(context.holidays, usr => usr.Id, hol => hol.Employee,
                //    (usr, hol) => new { usr, hol })
                //    .Where(m => m.hol.Status == 0 && m.hol.Manager == logUserEmail).
                //    Select(r => new
                //    {
                //        fName = r.usr.FirstName,
                //        lName = r.usr.LastName,
                //        eMail = r.usr.Email,
                //        sDate = r.hol.StartDate,
                //        eDate = r.hol.EndDate
                //    }).ToList();
                return View(results);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }

        }

        //[HttpPost]
        //public ActionResult Index(FormCollection collection)
        //{
        //    return View();
        //}
    }
}

WebApplication11/Controllers/RolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication11.Models;

namespace WebApplication11.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();
        
        // GET: Roles
        public ActionResult Index()
        {
            return View(context.Roles.ToList());
        }

        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                context.Roles.Add(new IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                return View("Create");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(string RoleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Create");
        }

        // GET: /Roles/Edit
        public ActionResult Edit(string roleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        
        // POST: /Roles/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: /Roles/Manage
        public ActionResult Manage()
        {
            var items = context.Roles.ToList();
            if (items != null)
            {
                ViewBag.data = items;
            }
            

            return View();
            //return View(context.Roles.ToList());
        }


        // POST: /Roles/Manage
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Manage(FormCollection collection)//, IdentityUserRole i)
        {

            //try
            //{
            //    context.Entry(role).State = System.Data.Entity.EntityState.Modified;
            //    context.SaveChanges();

            //    return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return View();
            //}

            var items = context.Roles.ToList();
            if (items != null)
            {
                ViewBag.data = items;
            }

            try
            {
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

                var user = UserManager.FindByName(collection["Employee"]);
                UserManager.AddToRole(user.Id, collection["RoleListBox"]);
                context.SaveChanges();

                ViewBag.ResultMessage = "Role added successfully !";
                return View("Manage");
            }
            catch
            {
                return View("Manage");
            }
            
        }
    }
}

WebApplication11/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Evidencija Odmora</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <!-- jQuery UI CSS Reference -->
        <link href="@Url.Content("~/Content/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" />
        <!-- Required jQuery and jQuery UI Javascript references -->
        <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui-1.10.4.min.js")"></script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Evidencija Odmora", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("User Information", "About", "Home")</li>
                        <li>@Html.ActionLink("Manage User", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Holiday Request", "Index", "RequestHoliday")</li>
                        <li>@Html.ActionLink("Role", "Index", "Roles")</li>
                        <li>@Html.ActionLink("Non working days", "Index", "NonWorkingDay")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Evidencija Odmora</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        @Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/cssjqryUi")
        <script type="text/javascript">
                $(document).ready(function () {
                    $('input[type=datetime]').datepicker({
                        dateFormat: "dd/M/yy",
                        changeMonth: true,
                        changeYear: true,
                        yearRange: "-60:+0"
                    });
                });
        </script>
    </body>
    </html>*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Evidencija Odmora</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/cssjqryUi")
    <!-- jQuery UI CSS Reference -->
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" />
    <!-- Required jQuery and jQuery UI Javascript references -->
    @*<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>*@



    @*<script src="@Url.Content("~/Scripts/jquery-ui-1.10.4.min.js")"></script>*@


    <link href="@Url.Content("~/Content/css/select2.min.css")" rel="stylesheet" />
    @*@Scripts.Render("~/bundles/jquery")*@
    <script src="@Url.Content("~/Scripts/jquery-1.12.4.js")"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @*@Scripts.Render("~/bundles/jqueryui")*@



    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.js")"></script>
    <script src="@Url.Content("~/Scripts/select2.js")"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Evidencija Odmora", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("User Information", "About", "Home")</li>
                    <li>@Html.ActionLink("Manage User", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Non working days", "Index", "NonWorkingDay")</li>
                    <li>@Html.ActionLink("Role", "Index", "Roles")</li>
                    <li>@Html.ActionLink("Non working days", "Index", "NonWorkingDay")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Evidencija Odmora</p>
        </footer>
    </div>

    @*<script type="text/javascript">
            $(document).ready(function () {

                //$('input[type=datetime]').datepicker({
                //    dateFormat: "dd/M/yy",
                //    changeMonth: true,
                //    changeYear: true,
                //    yearRange: "-60:+0",
                //    minDate: new Date()
                //});
                //$('#StartDate').datepicker({
                //    startDate: '-0d'
                //});
            });
        </script>*@

</body>
</html>